resources:
  - name: dwpdigital-cert-retriever
    type: registry-image-resource
    source:
      repository: dwpdigital/cert-retriever
    check_every: 5m

  - name: ecr-dwpdigital-cert-retriever-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "cert-retriever"

  - name: ecr-dwpdigital-cert-retriever
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "cert-retriever"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-cert-retriever-dev
    serial_groups: [cert-retriever]
    plan:
      - get: dwpdigital-cert-retriever
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-cert-retriever-dev
        params:
          image: "dwpdigital-cert-retriever/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-cert-retriever
    serial_groups: [cert-retriever]
    plan:
      - get: dwpdigital-cert-retriever
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-cert-retriever
        params:
          image: "dwpdigital-cert-retriever/image.tar"
        attempts: 3
